meta_product_name: "musique.wtf"
meta_title: "Musique.wtf - Where's The Funk"
meta_description: " Musique is a global community for musicians to connect, collaborate and share their passion. Join for free to access resources and opportunities, form bands, showcase your music, and collaborate on projects with fellow musicians. All music enthusiasts are welcome!"
meta_image: "homepage-og.jpg"
